EXERCISE_EVEN = 'Answer "yes" if the number is even, otherwise answer "no".'
EXERCISE_CALC = 'What is the result of the expression?'
EXERCISE_GCD = 'Find the greatest common divisor of given numbers.'
EXERCISE_PROGRESSION = 'What number is missing in the progression?'
EXERCISE_PRIME = 'Answer "yes" if given number is prime. Otherwise answer "no".'